[package]
name = "cyberdeck"
version.workspace = true
edition.workspace = true
default-run = "cyberdeck"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
deck-tauri = { workspace = true }
deck-core = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
