//! Rendering the systemd unit file for an engine profile: argument building
//! and the final unit text. Pure — no touch of the running service.

use std::path::PathBuf;

use deck_core::profile::{Engine, Profile};

pub(crate) fn systemd_dir() -> PathBuf {
    std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config")))
        .unwrap_or_else(|| PathBuf::from(".config"))
        .join("systemd/user")
}

pub(crate) fn generated_dir() -> PathBuf {
    std::env::var_os("XDG_DATA_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".local/share")))
        .unwrap_or_else(|| PathBuf::from(".local/share"))
        .join("cyberdeck/generated")
}

/// Builds the `ExecStart` argument list for an engine from a profile.
pub fn build_args(p: &Profile) -> Vec<String> {
    match p.engine {
        Engine::LlamaCpp => {
            let mut a = vec![
                "-m".into(),
                p.model.clone(),
                "--alias".into(),
                p.alias.clone(),
                "--ctx-size".into(),
                p.ctx_size.to_string(),
                "--n-gpu-layers".into(),
                p.n_gpu_layers.to_string(),
                "--ubatch-size".into(),
                p.ubatch_size.to_string(),
                "--parallel".into(),
                p.parallel.to_string(),
                "--temp".into(),
                p.temperature.to_string(),
                "--top-p".into(),
                p.top_p.to_string(),
                "--top-k".into(),
                p.top_k.to_string(),
                "--port".into(),
                p.port.to_string(),
                "--host".into(),
                p.host.clone(),
            ];
            if p.metrics {
                a.push("--metrics".into());
            }
            if p.flash_attn {
                a.push("--flash-attn".into());
                a.push("on".into());
            }
            if let Some(k) = &p.kv_cache_type_k {
                a.push("--cache-type-k".into());
                a.push(k.clone());
            }
            if let Some(v) = &p.kv_cache_type_v {
                a.push("--cache-type-v".into());
                a.push(v.clone());
            }
            if let Some(lm) = &p.load_mode {
                a.push("--load-mode".into());
                a.push(lm.clone());
            }
            if let Some(s) = &p.spec_type {
                a.push("--spec-type".into());
                a.push(s.clone());
            }
            if let Some(d) = &p.draft_model {
                a.push("--draft-model".into());
                a.push(d.display().to_string());
            }
            for (flag, val) in [
                ("reasoning", &p.reasoning),
                ("reasoning-format", &p.reasoning_format),
                ("reasoning-effort", &p.reasoning_effort),
            ] {
                if let Some(v) = val {
                    a.push(format!("--{flag}"));
                    a.push(v.clone());
                }
            }
            if let Some(b) = p.reasoning_budget {
                a.push("--reasoning-budget".into());
                a.push(b.to_string());
            }
            a
        }
        Engine::FreeToken => {
            let mut a = vec![
                "serve".into(),
                "--model".into(),
                p.model.clone(),
                "--host".into(),
                p.host.clone(),
                "--port".into(),
                p.port.to_string(),
            ];
            if let Some(b) = &p.ft_backend {
                a.push("--moe-backend".into());
                a.push(b.clone());
            }
            if let Some(c) = p.ft_moe_cache_size {
                a.push("--moe-cache-size".into());
                a.push(c.to_string());
            }
            a
        }
        Engine::Ollama => {
            // A daemon, not a per-model launch: no model path at exec time and
            // no host/port flags — Ollama binds via the OLLAMA_HOST env
            // rendered by `render_unit`. Models are addressed per-request by id
            // via /api/chat (see EngineProtocol::OllamaChat).
            vec!["serve".into()]
        }
    }
}

/// Renders the full systemd unit file content.
pub fn render_unit(p: &Profile) -> String {
    let args = build_args(p);
    let exec = format!("{} {}", p.bin.display(), shell_join(&args));
    let mut s = String::new();
    s.push_str(&format!(
        "# generated by cyberdeck — profile '{}'\n",
        p.name
    ));
    s.push_str("[Unit]\n");
    s.push_str(&format!(
        "Description=cyberdeck: {} ({})\n",
        p.name,
        p.engine.descriptor().display
    ));
    s.push_str("After=network.target\n\n");
    s.push_str("[Service]\n");
    s.push_str("Type=simple\n");
    s.push_str(&format!("ExecStart={exec}\n"));
    s.push_str("Restart=on-failure\n");
    s.push_str("RestartSec=5\n");
    if p.engine == Engine::LlamaCpp {
        s.push_str("Environment=LLAMACPP_API_KEY=llamacpp-local\n");
    }
    if p.engine == Engine::Ollama {
        // Ollama binds where OLLAMA_HOST points; the port contract lives here,
        // not in ExecStart args (ollama serve takes no --host/--port flags).
        s.push_str(&format!("Environment=OLLAMA_HOST={}:{}\n", p.host, p.port));
    }
    if let Some(m) = p.mem_max_mb {
        s.push_str(&format!("MemoryMax={}M\n", m));
    }
    if let Some(m) = p.mem_swap_max_mb {
        s.push_str(&format!("MemorySwapMax={}M\n", m));
    }
    s.push_str("\n[Install]\n");
    s.push_str("WantedBy=default.target\n");
    s
}

fn shell_join(args: &[String]) -> String {
    args.iter()
        .map(|a| {
            if a.contains(' ') || a.contains('"') {
                format!("\"{}\"", a.replace('"', "\\\""))
            } else {
                a.clone()
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}
